### ISSUE TITLE
Is this package automaticly redirect user to bank's page when call pay() function?

### ISSUE THREAD

**Issue by mrmmg** [idpay/laravel#1]
## Detailed description

I used this package for my laravel application and it's working finally but I have a question when I create the invoice and call `Payment::purchase()->pay()` everything is ok and the method shows me a URL with GET method, example: 
`{"action":"https:\/\/idpay.ir\/p\/ws-sandbox\/ecdskfoldskflkdsflkdsfowesfkes565654","inputs":[],"method":"GET"}`
it's okay, but I must redirect the user to the bank's page manually or the package to this automatically?

## Possible implementation

Nothing for now

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used: php 7.4 / Laravel 7.x
* Operating system and version: Windows 10 - Xampp local machine

**Comment by khanzadimahdi** [comment]
you must redirect it yourself or run `render` method.

```php
// Do all things together in a single line.
return Payment::purchase(
    (new Invoice)->amount(1000), 
    function($driver, $transactionId) {
    	// Store transactionId in database.
        // We need the transactionId to verify payment in the future.
    }
)->pay()->render();
```

**Comment by mrmmg** [comment]
thank you...
another method is save the payment in a variable and return it with double quotation, eg:

`$variable = Payment::purchase(
    (new Invoice)->amount(1000), 
    function($driver, $transactionId) {
    	// Store transactionId in database.
        // We need the transactionId to verify payment in the future.
    }
)->pay();`

return "$variable";

this method use shetabit redirect form in resources/views/vendor/shetabitPayment
