### ISSUE TITLE
Error code 0 in laravel 7

### ISSUE THREAD

**Issue by mrmmg** [idpay/laravel#2]
## Detailed description

**This error occurred in laravel with error code 0**:

`#0 /home1/bitir1/mrmmg/vendor/shetabit/multipay/src/Payment.php(212): Shetabit\\Multipay\\Drivers\\Idpay\\Idpay->purchase()
#1 /home1/bitir1/mrmmg/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Shetabit\\Multipay\\Payment->purchase(Object(Shetabit\\Multipay\\Invoice), Object(Closure))
#2 /home1/bitir1/mrmmg/app/Http/Controllers/PaymentController.php(50): Illuminate\\Support\\Facades\\Facade::__callStatic('purchase', Array)
#3 [internal function]: App\\Http\\Controllers\\PaymentController->pay(Object(Illuminate\\Http\\Request))`

any solution?

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 7.2, HHVM 3): PHP 7.4, Laravel 7
* Operating system and version (e.g. Ubuntu 19.04, Windows 10): CloudLinux
* Link to your project: [https://mrmmg.ir](https://mrmmg.ir)

**Comment by mrmmg** [comment]
@khanzadimahdi 
Hi, the idpay only works in sandbox mode and not working in real mode. it seems the idpay response. 
I follow the error and the Idpay.php line 116 returns an exception.
![image](https://user-images.githubusercontent.com/30490118/91664395-4e0b9580-eb04-11ea-8b93-424dba7afc03.png)
it seems that the idpay response is empty or something else. 

can you help me to solve this error?

**Comment by khanzadimahdi** [comment]
have you published vendor files?

```bash
php artisan vendor:publish
```

and have you change the payment.php in your config path?

**Comment by mrmmg** [comment]
yes, I have published the vendor files. it's worked before but suddenly this error occurred.

yes, I changed it and add idpay API KEY. also I changed the default key. that's it.

**Comment by khanzadimahdi** [comment]
remove `config/payment.php` and republish it please. then test and let me know if problem exists or not.

**Comment by mrmmg** [comment]
@khanzadimahdi
I removed `config/payment.php` and `views files` and republished both of them, also i changed my API KEY form idpay dashboard. for first time it seems the previous problem solved but a new error with code 500. the laravel log:
```
cURL error 6: Could not resolve host: api.idpay.ir (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 6: Could not resolve host: api.idpay.ir (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /home1/bitir1/mrmmg/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200)
```
I tried a second time and this time the previous problem still exists.
![Annotation 2020-08-31 092852](https://user-images.githubusercontent.com/30490118/91684444-cb6af080-eb6c-11ea-8d30-48026d392985.png)

**Comment by khanzadimahdi** [comment]
i think the api address might has changed! i must read IDPAY docs again and see if they have had any changes or not.

**Comment by mrmmg** [comment]
@khanzadimahdi 
That's right, so please leave this issue open and let me know the result.

**Comment by khanzadimahdi** [comment]
this issue is not active any more. so i close it.
